
[DB]
#HIST_DATA_CONN_STR=DRIVER={ODBC Driver 18 for SQL Server};SERVER=157.173.123.207,1433;DATABASE=SecuritiesHistoricalData_Light;UID=sa;PWD=Baiano10$12;MARS_Connection=Yes;TrustServerCertificate=yes
#ML_REPORTS_CONN_STR=DRIVER={ODBC Driver 18 for SQL Server};SERVER=157.173.123.207,1433,1433;DATABASE=machine_learning_research;UID=sa;PWD=Baiano10$12;MARS_Connection=Yes;TrustServerCertificate=yes
#FUND_MGMT_DASHBOARD_CS=DRIVER={ODBC Driver 18 for SQL Server};SERVER=157.173.123.207,1433,1433;DATABASE=fund_mgmt_dashboard;UID=sa;PWD=Baiano10$12;MARS_Connection=Yes;TrustServerCertificate=yes

HIST_DATA_CONN_STR=DRIVER={ODBC Driver 18 for SQL Server};SERVER=localhost;DATABASE=SecuritiesHistoricalData_Light;UID=sa;PWD=Baiano10$12;MARS_Connection=Yes;TrustServerCertificate=yes
ML_REPORTS_CONN_STR=DRIVER={ODBC Driver 18 for SQL Server};SERVER=localhost,1433;DATABASE=machine_learning_research;UID=sa;PWD=Baiano10$12;MARS_Connection=Yes;TrustServerCertificate=yes
FUND_MGMT_DASHBOARD_CS=DRIVER={ODBC Driver 18 for SQL Server};SERVER=localhost,1433;DATABASE=fund_mgmt_dashboard;UID=sa;PWD=Baiano10$12;MARS_Connection=Yes;TrustServerCertificate=yes

[GRAPH_DB]
NEO4J_URI =bolt://localhost:7687
NEO4J_USER =neo4j
NEO4J_PASS =test1234

[QDRANT]
QDRANT_SERVER=localhost
QDRANT_PORT=6333

[LANGFUSE]
LANGFUSE_SECRET_KEY=sk-lf-ed464eea-b670-44ff-b551-9bda406f8313
LANGFUSE_PUBLIC_KEY=pk-lf-80badbee-8e7b-4c13-a823-a80d354925bd
LANGFUSE_BASE_URL=https://us.cloud.langfuse.com

[MCP_OBSERVABILITY]
OBSERVABILITY_PROXY_URL=http://157.173.123.207:7003


[SETTINGS]
IB_PROD_WS=ws://66.94.106.206:7172
IB_DEV_WS=ws://66.94.106.206:8182
#PRIMARY_PROD_WS=ws://66.94.106.206:7173
PRIMARY_PROD_WS=ws://127.0.0.1:6162
CLASSIFICATION_MAP_KEY=SPY_TRADING
FRED_API_KEY=f2ce50dffe53ff839d739d66cdc4ed3c
TRADING_VIEW_USER=alien.zimzum@gmail.com
TRADING_VIEW_PWD=Baiano10$12$13
BCRA_API_KEY=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTIzNDAzNjEsInR5cGUiOiJleHRlcm5hbCIsInVzZXIiOiJhbGllbi56aW16dW1AZ21haWwuY29tIn0.Br4Kr6e2_MUHgXIMc6Lf-9VWXDsfdg7fgHDsDlLK_cymxLlqrkgSor9yVUdpU-0VzVnLOgtSWPUTJ9QZfSyL9w
#VPS --> 66.94.106.206


[FOLDERS]
OUTPUT_RF_FOLDER=./output/sliding_rf_models
OUTPUT_SECURITIES_REPORTS_FOLDER=output\securities_reports


[UI]
UI_PORT=9000

[ML_FLOW]
MLFLOW_TRACKING_URI=http://157.173.123.207:80

[GRAFANA]
LOKI_URL=http://157.173.123.207:3100
GRAFANA_ON=False


[EMBEDDINGS]
RAG_OUTPUT_FOLDER = ./output/rag
